### ISSUE TITLE
Tmpdir in DocxDocument does not exist

### ISSUE THREAD

**Issue by viancen** [bingo-soft/phpdocxtemplate#3]
Hello, was testing around with this package, one thing is not working out of the box: the tmpDir variable in DocxDocument. Could you make this a configurable value?  for example something like:

```
    /**
     * Construct an instance of PhpDocxTemplate
     *
     * @param string $path - path to the template
     */
    public function __construct(string $path , $tmpDir = null)
    {
        $this->docx = new DocxDocument($path, $tmpDir);
        $this->crcToNewMedia = [];
        $this->crcToNewEmbedded = [];
        $this->picToReplace = [];
        $this->picMap = [];
    }
```

thanks!

**Comment by viancen** [comment]
Or even better maybe:
`$this->tmpDir = sys_get_temp_dir();`

**Comment by bingo-soft** [comment]
Hello. Fixed it

**Comment by viancen** [comment]
thanks, great package now :)

**Comment by viancen** [comment]
Hi, in the new release, the tmp path is back to './tmp' again... could you please update this again? thanks alot
